export function railwayToml(): string {
  return `[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
`
}

export function renderYaml(): string {
  return `services:
  - type: web
    name: quipthread
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: /data/db.sqlite
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: TRUST_PROXY
        value: "true"
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
`
}

export function railwayInstructions(): string {
  return [
    '1. Push this project to a GitHub repository.',
    '2. Go to https://railway.app and create a new project.',
    '3. Select "Deploy from GitHub repo" and connect your repository.',
    '4. Railway detects the Dockerfile and railway.toml automatically.',
    '5. Add your environment variables under Settings → Variables.',
    '   Copy values from .env; use the platform hostname or custom domain for BASE_URL.',
    '   Set DATABASE_URL=/data/db.sqlite and TRUST_PROXY=true.',
    '6. Add a persistent volume under Settings → Volumes.',
    '   Mount path: /data',
    '7. Railway deploys automatically on every push to main.',
  ].join('\n')
}

export function renderInstructions(): string {
  return [
    '1. Push this project to a GitHub repository.',
    '2. Go to https://render.com and choose New → Blueprint.',
    '3. Connect your GitHub repository.',
    '4. Render reads render.yaml from the connected repository.',
    '   JWT_SECRET is auto-generated by render.yaml.',
    '5. Add your remaining environment variables under Environment.',
    '   The Blueprint prompts for BASE_URL, publisher origins, and GitHub OAuth.',
    '   For Google or email auth, replace the GitHub entries before applying it.',
    '6. The persistent disk for /data is defined in render.yaml.',
    '7. Apply the Blueprint to deploy.',
  ].join('\n')
}

export function flyioInstructions(): string {
  return [
    'Fly.io generates its own fly.toml interactively via flyctl.',
    '',
    '1. Install flyctl:',
    '   https://fly.io/docs/hands-on/install-flyctl/',
    '',
    '2. Log in:',
    '   fly auth login',
    '',
    '3. Launch from your project directory (generates fly.toml):',
    '   fly launch --no-deploy',
    '',
    '4. Create a persistent volume for your database:',
    '   fly volumes create quipthread_data --size 1',
    '',
    '5. Update your fly.toml to mount the volume at /data:',
    '   [mounts]',
    '     source = "quipthread_data"',
    '     destination = "/data"',
    '',
    '6. Set your secrets (do not commit .env to your repo):',
    '   fly secrets import < .env',
    '   Use the Fly hostname or custom domain for BASE_URL, not localhost.',
    '   Set TRUST_PROXY=true and http_service.internal_port=8080 in fly.toml.',
    '',
    '   Keep one Machine for this SQLite volume; do not create independent replicas.',
    '',
    '7. Deploy:',
    '   fly deploy --ha=false',
  ].join('\n')
}
