export function railwayToml(): string {
  return `[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
`
}

export function renderYaml(): string {
  return `services:
  - type: web
    name: quipthread
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: /data/comments.db
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        generateValue: true
`
}

export function railwayInstructions(): string {
  return [
    '1. Push this project to a GitHub repository.',
    '2. Go to https://railway.app and create a new project.',
    '3. Select "Deploy from GitHub repo" and connect your repository.',
    '4. Railway detects the Dockerfile and railway.toml automatically.',
    '5. Add your environment variables under Settings → Variables.',
    '   Copy all values from your .env file.',
    '6. Add a persistent volume under Settings → Volumes.',
    '   Mount path: /data',
    '7. Railway deploys automatically on every push to main.',
  ].join('\n')
}

export function renderInstructions(): string {
  return [
    '1. Push this project to a GitHub repository.',
    '2. Go to https://render.com → New → Web Service.',
    '3. Connect your GitHub repository.',
    '4. Render detects render.yaml and configures the service automatically.',
    '   JWT_SECRET is auto-generated by render.yaml.',
    '5. Add your remaining environment variables under Environment.',
    '   Copy all other values from your .env file.',
    '6. The persistent disk for /data is defined in render.yaml.',
    '7. Click "Create Web Service" to deploy.',
  ].join('\n')
}

export function flyioInstructions(): string {
  return [
    'Fly.io generates its own fly.toml interactively via flyctl.',
    '',
    '1. Install flyctl:',
    '   https://fly.io/docs/hands-on/install-flyctl/',
    '',
    '2. Log in:',
    '   fly auth login',
    '',
    '3. Launch from your project directory (generates fly.toml):',
    '   fly launch',
    '',
    '4. Create a persistent volume for your database:',
    '   fly volumes create quipthread_data --size 1',
    '',
    '5. Update your fly.toml to mount the volume at /data:',
    '   [mounts]',
    '     source = "quipthread_data"',
    '     destination = "/data"',
    '',
    '6. Set your secrets (do not commit .env to your repo):',
    '   fly secrets set JWT_SECRET=$(openssl rand -hex 32)',
    '   fly secrets set GITHUB_CLIENT_ID=... GITHUB_CLIENT_SECRET=...',
    '   # Repeat for all other values in your .env',
    '',
    '7. Deploy:',
    '   fly deploy',
  ].join('\n')
}
