name: CI (CLI)

on:
  push:
    branches: [main]
    paths:
      - "packages/create-quipthread/**"
  pull_request:
    paths:
      - "packages/create-quipthread/**"

jobs:
  cli:
    runs-on: blacksmith-2vcpu-ubuntu-2404 # blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Build CLI
        working-directory: packages/create-quipthread
        run: bun run build
